# Changes here will be overwritten by Copier.
_commit: 1.15.1
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2026'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
project_description: Python library to interact with Terminator through D-Bus.
project_name: Terminator D-Bus
python_package_command_line_name: terminator-dbus
python_package_distribution_name: terminator-dbus
python_package_import_name: terminator_dbus
repository_name: terminator-dbus
repository_namespace: pawamoy
repository_provider: github.com

